// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package serve

import (
	"github.com/nomkhonwaan/myblog/pkg/facebook"
	"github.com/nomkhonwaan/myblog/pkg/mongo"
	"github.com/nomkhonwaan/myblog/pkg/storage"
)

// Injectors from wire.go:

func initFacebookHandler(db mongo.Database) *facebook.Handler {
	fileRepository := storage.NewFileRepository(db)
	handler := facebook.NewHandler(fileRepository)
	return handler
}
