version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  install:
    docker:
      - image: circleci/golang:1.13
        environment:
            GO111MODULE: "on"
    working_directory: ~/repo
    steps:
      - checkout
      - run: make install
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
  test:
    docker:
      - image: circleci/golang:1.13
        environment:
            GO111MODULE: "on"
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: make test
      - codecov/upload:
          file: ./coverage.out
  build_docker_image:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: make build-docker-all-in-one
      - run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - run: docker push nomkhonwaan/myblog-all-in-one:latest
  deploy_to_docker_deploy_webhook:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - run: |
          curl \
            -H 'Content-Type: application/json' \
            -d '{"repository": {"repo_name": "nomkhonwaan/myblog-all-in-one"}, "push_data": {"tag": "latest"}}' \
            ${DOCKER_DEPLOY_WEBHOOK_URL}
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - build_docker_image:
          requires:
            - test
      - deploy_to_docker_deploy_webhook:
          requires:
            - build_docker_image
