// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nomkhonwaan/myblog/pkg/graphql (interfaces: Service)

// Package mock_graphql is a generated GoMock package.
package mock_graphql

import (
	gomock "github.com/golang/mock/gomock"
	blog "github.com/nomkhonwaan/myblog/pkg/blog"
	storage "github.com/nomkhonwaan/myblog/pkg/storage"
	reflect "reflect"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Category mocks base method
func (m *MockService) Category() blog.CategoryRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Category")
	ret0, _ := ret[0].(blog.CategoryRepository)
	return ret0
}

// Category indicates an expected call of Category
func (mr *MockServiceMockRecorder) Category() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Category", reflect.TypeOf((*MockService)(nil).Category))
}

// File mocks base method
func (m *MockService) File() storage.FileRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "File")
	ret0, _ := ret[0].(storage.FileRepository)
	return ret0
}

// File indicates an expected call of File
func (mr *MockServiceMockRecorder) File() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "File", reflect.TypeOf((*MockService)(nil).File))
}

// Post mocks base method
func (m *MockService) Post() blog.PostRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post")
	ret0, _ := ret[0].(blog.PostRepository)
	return ret0
}

// Post indicates an expected call of Post
func (mr *MockServiceMockRecorder) Post() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockService)(nil).Post))
}

// Tag mocks base method
func (m *MockService) Tag() blog.TagRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tag")
	ret0, _ := ret[0].(blog.TagRepository)
	return ret0
}

// Tag indicates an expected call of Tag
func (mr *MockServiceMockRecorder) Tag() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tag", reflect.TypeOf((*MockService)(nil).Tag))
}
